# source: https://github.com/tiangolo/uvicorn-gunicorn-docker/blob/master/docker-images/python3.10-slim.dockerfile
FROM python:3.10-slim

COPY . .

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

ARG TRAINING_PORT
ENV PORT=$TRAINING_PORT
EXPOSE $PORT

ENTRYPOINT [ "bash" ]